<?php

namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\GenerateQuestionsRequest;
use App\Http\Requests\StoreMaterialRequest;
use App\Http\Resources\MaterialDetailResource;
use App\Services\MaterialService;
use App\Traits\ApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class MaterialController extends Controller
{
    use ApiResponse;

    public function __construct(
        protected MaterialService $materialService
    ) {}

    /**
     * Create a new material (AI auto-generates 23-32 questions).
     */
    public function store(StoreMaterialRequest $request): JsonResponse
    {
        $result = $this->materialService->create(
            $request->validated(),
            $request->user()
        );

        $message = "Material created successfully. {$result['questions_generated']} questions generated by AI.";

        if ($result['ai_error']) {
            $message .= " Warning: AI generation had an issue — {$result['ai_error']}";
        }

        return $this->success(
            new MaterialDetailResource($result['material']),
            $message,
            201
        );
    }

    /**
     * Regenerate questions for an existing material using AI.
     */
    public function generateQuestions(GenerateQuestionsRequest $request, int $id): JsonResponse
    {
        $count = $request->validated()['count'] ?? null;

        $result = $this->materialService->regenerateQuestions($id, $count);

        if ($result['ai_error']) {
            return $this->error(
                "Failed to generate questions: {$result['ai_error']}",
                500
            );
        }

        return $this->success(
            new MaterialDetailResource($result['material']),
            "{$result['questions_generated']} questions regenerated successfully"
        );
    }
}
